const payruns = [
	{
		id: 1,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'Alice Johnson',
		TOTAL_EMPLOYEES: 150,
		LAST_UPDATED: 'June 25 2024',
		PAY_PERIOD: 'June 1 2024',
		STATUS: 'Approved',
	},
	{
		id: 2,
		PAY_FREQUENCY: 'Bi-Weekly',
		CREATED_BY: 'Bob Williams',
		TOTAL_EMPLOYEES: 230,
		LAST_UPDATED: 'June 20 2024',
		PAY_PERIOD: 'June 1 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 3,
		PAY_FREQUENCY: 'Weekly',
		CREATED_BY: 'Charlie Brown',
		TOTAL_EMPLOYEES: 80,
		LAST_UPDATED: 'June 26 2024',
		PAY_PERIOD: 'June 17 2024',
		STATUS: 'Scheduled',
	},
	{
		id: 4,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'David Lee',
		TOTAL_EMPLOYEES: 180,
		LAST_UPDATED: 'May 31 2024',
		PAY_PERIOD: 'May 1 2024',
		STATUS: 'Approved',
	},
	{
		id: 5,
		PAY_FREQUENCY: 'Bi-Weekly',
		CREATED_BY: 'Eve Davis',
		TOTAL_EMPLOYEES: 210,
		LAST_UPDATED: 'June 22 2024',
		PAY_PERIOD: 'June 15 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 6,
		PAY_FREQUENCY: 'Weekly',
		CREATED_BY: 'Frank White',
		TOTAL_EMPLOYEES: 95,
		LAST_UPDATED: 'June 27 2024',
		PAY_PERIOD: 'June 24 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 7,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'Grace Taylor',
		TOTAL_EMPLOYEES: 165,
		LAST_UPDATED: 'June 20 2024',
		PAY_PERIOD: 'June 1 2024',
		STATUS: 'Approved',
	},
	{
		id: 8,
		PAY_FREQUENCY: 'Bi-Weekly',
		CREATED_BY: 'Harry Green',
		TOTAL_EMPLOYEES: 200,
		LAST_UPDATED: 'June 19 2024',
		PAY_PERIOD: 'May 15 2024',
		STATUS: 'Scheduled',
	},
	{
		id: 9,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'Ivy Rodriguez',
		TOTAL_EMPLOYEES: 130,
		LAST_UPDATED: 'July 24 2024',
		PAY_PERIOD: 'July 1 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 10,
		PAY_FREQUENCY: 'Weekly',
		CREATED_BY: 'Jack Smith',
		TOTAL_EMPLOYEES: 75,
		LAST_UPDATED: 'July 25 2024',
		PAY_PERIOD: 'July 22 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 11,
		PAY_FREQUENCY: 'Bi-Weekly',
		CREATED_BY: 'Karen Lee',
		TOTAL_EMPLOYEES: 190,
		LAST_UPDATED: 'July 18 2024',
		PAY_PERIOD: 'July 15 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 12,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'Liam Chen',
		TOTAL_EMPLOYEES: 220,
		LAST_UPDATED: 'August 30 2024',
		PAY_PERIOD: 'August 1 2024',
		STATUS: 'Pending Approval',
	},
	{
		id: 13,
		PAY_FREQUENCY: 'Weekly',
		CREATED_BY: 'Mia Kim',
		TOTAL_EMPLOYEES: 60,
		LAST_UPDATED: 'August 29 2024',
		PAY_PERIOD: 'August 26 2024',
		STATUS: 'Approved',
	},
	{
		id: 14,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'Noah Davis',
		TOTAL_EMPLOYEES: 170,
		LAST_UPDATED: 'September 20 2024',
		PAY_PERIOD: 'September 1 2024',
		STATUS: 'Scheduled',
	},
	{
		id: 15,
		PAY_FREQUENCY: 'Bi-Weekly',
		CREATED_BY: 'Olivia Clark',
		TOTAL_EMPLOYEES: 205,
		LAST_UPDATED: 'October 10 2024',
		PAY_PERIOD: 'October 7 2024',
		STATUS: 'Approved',
	},
	{
		id: 16,
		PAY_FREQUENCY: 'Weekly',
		CREATED_BY: 'Peter Evans',
		TOTAL_EMPLOYEES: 90,
		LAST_UPDATED: 'November 15 2024',
		PAY_PERIOD: 'November 11 2024',
		STATUS: 'Approved',
	},
	{
		id: 17,
		PAY_FREQUENCY: 'Monthly',
		CREATED_BY: 'Quinn Walker',
		TOTAL_EMPLOYEES: 145,
		LAST_UPDATED: 'December 28 2024',
		PAY_PERIOD: 'December 1 2024',
		STATUS: 'Pending Approval',
	},
];

export {payruns}