import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import AppSidebar from './components/sidebar';
import Navigation from './components/Nav';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'ExxForce',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
			<div className=' w-full mb-3'>
				<SidebarProvider>
					<AppSidebar className='bg-black' />
					<div className='grid w-full'>
						<Navigation />
						<main className='w-full'>{children}</main>
					</div>
				</SidebarProvider>
			</div>
		</body>
	);
}
